In [1]:
import pandas as pd
from bayes_opt import BayesianOptimization
import lightgbm as lgb
import numpy as np

In [2]:
df = pd.read_csv('rubinstein_generacion.txt.gz',sep='\t')

In [3]:
df['clase01'] = df.clase.apply(lambda x: 1 if x=='SI' else 0)
del df['clase']

In [5]:
model_pandas = lgb.LGBMClassifier()
model_nparray = lgb.LGBMClassifier()


In [6]:
labels = df['clase01']
features = np.array(df.drop(columns=['clase01']))
feature_names = list(df.drop(columns=['clase01']).columns)


In [32]:
ds_pandas = lgb.Dataset(data=df.drop(columns=['clase01']),label=df['clase01'])


In [33]:
ds_nparray = lgb.Dataset(data=features, label=labels, feature_name=feature_names)

In [9]:
model_pandas.fit(X = ds_pandas.data,
    y = ds_pandas.label
    )

LGBMClassifier()

In [10]:
model_nparray.fit(X = ds_nparray.data,
    y = ds_nparray.label,
    feature_name = ds_nparray.feature_name
    )

LGBMClassifier()

In [11]:
model_pandas_direct = lgb.train({},train_set = ds_pandas)

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.206639 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18631
[LightGBM] [Info] Number of data points in the train set: 105000, number of used features: 147
[LightGBM] [Info] Start training from score 0.081229


In [12]:
model_nparray_direct = lgb.train({},train_set = ds_nparray)

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.083059 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18631
[LightGBM] [Info] Number of data points in the train set: 105000, number of used features: 147
[LightGBM] [Info] Start training from score 0.081229


In [28]:
model_pandas_direct_cv = lgb.cv({},train_set = ds_pandas)

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.186946 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18631
[LightGBM] [Info] Number of data points in the train set: 84000, number of used features: 147
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.601003 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18631
[LightGBM] [Info] Number of data points in the train set: 84000, number of used features: 147
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.854400 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18631
[LightGBM] [Info] Number of data points in the train set: 84000, number of used features: 147
[LightGBM] [Warning] Auto-choosing col-wise multi-thre

In [38]:
model_pandas_direct_cv['l2-mean']

[0.07065296146316392,
 0.0674132198060203,
 0.06473066878040556,
 0.062494314377812055,
 0.060608401988118364,
 0.05899404198586433,
 0.05764451602537758,
 0.0565162002386991,
 0.055554563090797,
 0.05471830086159359,
 0.05403475893608569,
 0.053417060949239516,
 0.05290955785891697,
 0.05247114518062405,
 0.05209024155854839,
 0.05176398525772933,
 0.051473440706592696,
 0.051233266889479566,
 0.05102594888879204,
 0.050828791446993704,
 0.05065806456846631,
 0.05050262055948126,
 0.05036154108984594,
 0.05021733883333015,
 0.05010269864892845,
 0.05000594088777464,
 0.0499128488429745,
 0.04982616774473577,
 0.049740557621406306,
 0.049661982654644735,
 0.0496080027502621,
 0.04954201961728699,
 0.049493907252191625,
 0.04944582228754617,
 0.049413396209059615,
 0.04937140207513423,
 0.04935169263687398,
 0.04932873175972848,
 0.04928933596851415,
 0.04923606001116625,
 0.04922113881749327,
 0.04919646649428942,
 0.049179751190205734,
 0.04915621383327047,
 0.04913959357337923,
 0.04

In [29]:
model_nparray_direct_cv = lgb.cv({},train_set = ds_nparray)

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.503568 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18631
[LightGBM] [Info] Number of data points in the train set: 105000, number of used features: 147
[LightGBM] [Info] Start training from score 0.081229


In [19]:
model_pandas.predict_proba(ds_pandas.data)

array([[0.99081052, 0.00918948],
       [0.98679791, 0.01320209],
       [0.99041239, 0.00958761],
       ...,
       [0.93635729, 0.06364271],
       [0.92239419, 0.07760581],
       [0.96672874, 0.03327126]])

In [23]:
model_nparray.predict_proba(ds_nparray.data)

array([[0.99081052, 0.00918948],
       [0.98679791, 0.01320209],
       [0.99041239, 0.00958761],
       ...,
       [0.93635729, 0.06364271],
       [0.92239419, 0.07760581],
       [0.96672874, 0.03327126]])

In [25]:
model_pandas_direct.predict(ds_pandas.data)

array([0.00601915, 0.04068114, 0.00831606, ..., 0.04772452, 0.09222661,
       0.04249108])

In [26]:
model_nparray_direct.predict(ds_nparray.data)

array([0.00601915, 0.04068114, 0.00831606, ..., 0.04772452, 0.09222661,
       0.04249108])

In [35]:
model_pandas_direct_cv.predict(ds_pandas.data)

AttributeError: 'dict' object has no attribute 'predict'

In [34]:
model_nparray_direct_cv.predict(ds_nparray.data)

array([0.00601915, 0.04068114, 0.00831606, ..., 0.04772452, 0.09222661,
       0.04249108])